version: '3'
services: 
  db:
    image: mongo:3.4
  back-end:
    image: node:8.1
    volumes: 
      - ./back-end:/back-end
    ports: 
      - 3000:3000
    command: bash -c "cd /back-end && npm i && node app"      
  front-end:
    image: nginx:1.13
    volumes:
      - ./front-end:/usr/share/nginx/html/
    ports: 
      - 80:80